export const languages = [
  { label: "English", value: "en" },
  { label: "Spanish", value: "es" },
  { label: "French", value: "fr" },
  { label: "German", value: "de" },
  { label: "Italian", value: "it" },
  { label: "Portuguese", value: "pt" },
  { label: "Portuguese (Brazil)", value: "pt-BR" },
  { label: "Chinese (Simplified)", value: "zh-CN" },
  { label: "Chinese (Traditional)", value: "zh-TW" },
  { label: "Japanese", value: "ja" },
  { label: "Korean", value: "ko" },
  { label: "Russian", value: "ru" },
  { label: "Arabic", value: "ar" },
  { label: "Hindi", value: "hi" },
  { label: "Bengali", value: "bn" },
  { label: "Dutch", value: "nl" },
  { label: "Turkish", value: "tr" },
  { label: "Polish", value: "pl" },
  { label: "Indonesian", value: "id" },
  { label: "Vietnamese", value: "vi" },
  { label: "Thai", value: "th" },
  { label: "Swedish", value: "sv" },
  { label: "Greek", value: "el" },
  { label: "Czech", value: "cs" },
  { label: "Danish", value: "da" },
  { label: "Finnish", value: "fi" },
  { label: "Hungarian", value: "hu" },
  { label: "Norwegian", value: "no" },
  { label: "Romanian", value: "ro" },
  { label: "Slovak", value: "sk" },
  { label: "Ukrainian", value: "uk" },
  { label: "Hebrew", value: "he" },
  { label: "Malay", value: "ms" },
  { label: "Tagalog", value: "tl" },
  { label: "Swahili", value: "sw" },
  { label: "Afrikaans", value: "af" },
  { label: "Urdu", value: "ur" },
  { label: "Persian", value: "fa" },
  { label: "Serbian", value: "sr" },
  { label: "Croatian", value: "hr" },
  { label: "Bulgarian", value: "bg" },
];
