export const languages = [
  { label: "English", value: "en" },
  { label: "English (United States)", value: "en-US" },
  { label: "English (United Kingdom)", value: "en-GB" },
  { label: "English (Australia)", value: "en-AU" },
  { label: "English (Canada)", value: "en-CA" },
  { label: "English (India)", value: "en-IN" },
  { label: "English (New Zealand)", value: "en-NZ" },
  { label: "English (South Africa)", value: "en-ZA" },
  { label: "English (Cameroon)", value: "en-CM" },
  { label: "Cameroon Pidgin English", value: "cpe-CM" },
  { label: "Spanish", value: "es" },
  { label: "Spanish (Spain)", value: "es-ES" },
  { label: "Spanish (Mexico)", value: "es-MX" },
  { label: "Spanish (United States)", value: "es-US" },
  { label: "Spanish (Argentina)", value: "es-AR" },
  { label: "Spanish (Colombia)", value: "es-CO" },
  { label: "Spanish (Chile)", value: "es-CL" },
  { label: "Spanish (Peru)", value: "es-PE" },
  { label: "Spanish (Venezuela)", value: "es-VE" },
  { label: "French", value: "fr" },
  { label: "French (France)", value: "fr-FR" },
  { label: "French (Canada)", value: "fr-CA" },
  { label: "French (Belgium)", value: "fr-BE" },
  { label: "French (Switzerland)", value: "fr-CH" },
  { label: "French (Cameroon)", value: "fr-CM" },
  { label: "Portuguese", value: "pt" },
  { label: "Portuguese (Portugal)", value: "pt-PT" },
  { label: "Portuguese (Brazil)", value: "pt-BR" },
  { label: "German", value: "de" },
  { label: "German (Germany)", value: "de-DE" },
  { label: "German (Austria)", value: "de-AT" },
  { label: "German (Switzerland)", value: "de-CH" },
  { label: "Italian", value: "it" },
  { label: "Italian (Italy)", value: "it-IT" },
  { label: "Italian (Switzerland)", value: "it-CH" },
  { label: "Dutch", value: "nl" },
  { label: "Dutch (Netherlands)", value: "nl-NL" },
  { label: "Dutch (Belgium)", value: "nl-BE" },
  { label: "Dutch (Flemish)", value: "nl-BE-flemish" },
  { label: "Limburgish", value: "li" },
  { label: "Limburgish (Netherlands)", value: "li-NL" },
  { label: "Chinese", value: "zh" },
  { label: "Chinese (Simplified)", value: "zh-CN" },
  { label: "Chinese (Traditional)", value: "zh-TW" },
  { label: "Chinese (Hong Kong)", value: "zh-HK" },
  { label: "Chinese (Singapore)", value: "zh-SG" },
  { label: "Japanese", value: "ja" },
  { label: "Japanese (Japan)", value: "ja-JP" },
  { label: "Korean", value: "ko" },
  { label: "Korean (South Korea)", value: "ko-KR" },
  { label: "Russian", value: "ru" },
  { label: "Russian (Russia)", value: "ru-RU" },
  { label: "Arabic", value: "ar" },
  { label: "Arabic (Saudi Arabia)", value: "ar-SA" },
  { label: "Arabic (Egypt)", value: "ar-EG" },
  { label: "Arabic (United Arab Emirates)", value: "ar-AE" },
  { label: "Arabic (Morocco)", value: "ar-MA" },
  { label: "Arabic (Iraq)", value: "ar-IQ" },
  { label: "Hindi", value: "hi" },
  { label: "Hindi (India)", value: "hi-IN" },
  { label: "Bengali", value: "bn" },
  { label: "Bengali (Bangladesh)", value: "bn-BD" },
  { label: "Bengali (India)", value: "bn-IN" },
  { label: "Urdu", value: "ur" },
  { label: "Urdu (Pakistan)", value: "ur-PK" },
  { label: "Urdu (India)", value: "ur-IN" },
  { label: "Punjabi", value: "pa" },
  { label: "Punjabi (India)", value: "pa-IN" },
  { label: "Punjabi (Pakistan)", value: "pa-PK" },
  { label: "Gujarati", value: "gu" },
  { label: "Gujarati (India)", value: "gu-IN" },
  { label: "Marathi", value: "mr" },
  { label: "Marathi (India)", value: "mr-IN" },
  { label: "Kannada", value: "kn" },
  { label: "Kannada (India)", value: "kn-IN" },
  { label: "Malayalam", value: "ml" },
  { label: "Malayalam (India)", value: "ml-IN" },
  { label: "Tamil", value: "ta" },
  { label: "Tamil (India)", value: "ta-IN" },
  { label: "Tamil (Singapore)", value: "ta-SG" },
  { label: "Tamil (Sri Lanka)", value: "ta-LK" },
  { label: "Tamil (Malaysia)", value: "ta-MY" },
  { label: "Telugu", value: "te" },
  { label: "Telugu (India)", value: "te-IN" },
  { label: "Nepali", value: "ne" },
  { label: "Nepali (Nepal)", value: "ne-NP" },
  { label: "Sinhala", value: "si" },
  { label: "Sinhala (Sri Lanka)", value: "si-LK" },
  { label: "Thai", value: "th" },
  { label: "Thai (Thailand)", value: "th-TH" },
  { label: "Vietnamese", value: "vi" },
  { label: "Vietnamese (Vietnam)", value: "vi-VN" },
  { label: "Indonesian", value: "id" },
  { label: "Indonesian (Indonesia)", value: "id-ID" },
  { label: "Malay", value: "ms" },
  { label: "Malay (Malaysia)", value: "ms-MY" },
  { label: "Filipino", value: "fil" },
  { label: "Filipino (Philippines)", value: "fil-PH" },
  { label: "Tagalog", value: "tl" },
  { label: "Tagalog (Philippines)", value: "tl-PH" },
  { label: "Cebuano", value: "ceb" },
  { label: "Cebuano (Philippines)", value: "ceb-PH" },
  { label: "Ilocano", value: "ilo" },
  { label: "Ilocano (Philippines)", value: "ilo-PH" },
  { label: "Hiligaynon", value: "hil" },
  { label: "Hiligaynon (Philippines)", value: "hil-PH" },
  { label: "Waray", value: "war" },
  { label: "Waray (Philippines)", value: "war-PH" },
  { label: "Bikol", value: "bik" },
  { label: "Bikol (Philippines)", value: "bik-PH" },
  { label: "Kapampangan", value: "pam" },
  { label: "Kapampangan (Philippines)", value: "pam-PH" },
  { label: "Pangasinan", value: "pag" },
  { label: "Pangasinan (Philippines)", value: "pag-PH" },
  { label: "Maranao", value: "mrw" },
  { label: "Maranao (Philippines)", value: "mrw-PH" },
  { label: "Maguindanao", value: "mdh" },
  { label: "Maguindanao (Philippines)", value: "mdh-PH" },
  { label: "Tausug", value: "tsg" },
  { label: "Tausug (Philippines)", value: "tsg-PH" },
  { label: "Turkish", value: "tr" },
  { label: "Turkish (Turkey)", value: "tr-TR" },
  { label: "Polish", value: "pl" },
  { label: "Polish (Poland)", value: "pl-PL" },
  { label: "Czech", value: "cs" },
  { label: "Czech (Czechia)", value: "cs-CZ" },
  { label: "Slovak", value: "sk" },
  { label: "Slovak (Slovakia)", value: "sk-SK" },
  { label: "Hungarian", value: "hu" },
  { label: "Hungarian (Hungary)", value: "hu-HU" },
  { label: "Romanian", value: "ro" },
  { label: "Romanian (Romania)", value: "ro-RO" },
  { label: "Bulgarian", value: "bg" },
  { label: "Bulgarian (Bulgaria)", value: "bg-BG" },
  { label: "Greek", value: "el" },
  { label: "Greek (Greece)", value: "el-GR" },
  { label: "Ukrainian", value: "uk" },
  { label: "Ukrainian (Ukraine)", value: "uk-UA" },
  { label: "Hebrew", value: "he" },
  { label: "Hebrew (Israel)", value: "he-IL" },
  { label: "Persian", value: "fa" },
  { label: "Persian (Iran)", value: "fa-IR" },
  { label: "Swedish", value: "sv" },
  { label: "Swedish (Sweden)", value: "sv-SE" },
  { label: "Danish", value: "da" },
  { label: "Danish (Denmark)", value: "da-DK" },
  { label: "Norwegian", value: "no" },
  { label: "Norwegian (Norway)", value: "no-NO" },
  { label: "Finnish", value: "fi" },
  { label: "Finnish (Finland)", value: "fi-FI" },
  { label: "Icelandic", value: "is" },
  { label: "Icelandic (Iceland)", value: "is-IS" },
  { label: "Irish", value: "ga" },
  { label: "Irish (Ireland)", value: "ga-IE" },
  { label: "Welsh", value: "cy" },
  { label: "Welsh (United Kingdom)", value: "cy-GB" },
  { label: "Catalan", value: "ca" },
  { label: "Catalan (Spain)", value: "ca-ES" },
  { label: "Galician", value: "gl" },
  { label: "Galician (Spain)", value: "gl-ES" },
  { label: "Basque", value: "eu" },
  { label: "Basque (Spain)", value: "eu-ES" },
  { label: "Serbian", value: "sr" },
  { label: "Serbian (Serbia)", value: "sr-RS" },
  { label: "Croatian", value: "hr" },
  { label: "Croatian (Croatia)", value: "hr-HR" },
  { label: "Slovenian", value: "sl" },
  { label: "Slovenian (Slovenia)", value: "sl-SI" },
  { label: "Lithuanian", value: "lt" },
  { label: "Lithuanian (Lithuania)", value: "lt-LT" },
  { label: "Latvian", value: "lv" },
  { label: "Latvian (Latvia)", value: "lv-LV" },
  { label: "Estonian", value: "et" },
  { label: "Estonian (Estonia)", value: "et-EE" },
  { label: "Albanian", value: "sq" },
  { label: "Albanian (Albania)", value: "sq-AL" },
  { label: "Macedonian", value: "mk" },
  { label: "Macedonian (North Macedonia)", value: "mk-MK" },
  { label: "Bosnian", value: "bs" },
  { label: "Bosnian (Bosnia and Herzegovina)", value: "bs-BA" },
  { label: "Maltese", value: "mt" },
  { label: "Maltese (Malta)", value: "mt-MT" },
  { label: "Afrikaans", value: "af" },
  { label: "Afrikaans (South Africa)", value: "af-ZA" },
  { label: "Swahili", value: "sw" },
  { label: "Swahili (Kenya)", value: "sw-KE" },
  { label: "Swahili (Tanzania)", value: "sw-TZ" },
  { label: "Amharic", value: "am" },
  { label: "Amharic (Ethiopia)", value: "am-ET" },
  { label: "Hausa", value: "ha" },
  { label: "Hausa (Nigeria)", value: "ha-NG" },
  { label: "Igbo", value: "ig" },
  { label: "Igbo (Nigeria)", value: "ig-NG" },
  { label: "Yoruba", value: "yo" },
  { label: "Yoruba (Nigeria)", value: "yo-NG" },
  { label: "Duala (Cameroon)", value: "dua-CM" },
  { label: "Ewondo (Cameroon)", value: "ewo-CM" },
  { label: "Bassa (Cameroon)", value: "bas-CM" },
  { label: "Fulfulde (Cameroon)", value: "ff-CM" },
  { label: "Bamun (Cameroon)", value: "bax-CM" },
  { label: "Bafut (Cameroon)", value: "bfd-CM" },
  { label: "Ngemba (Cameroon)", value: "nge-CM" },
  { label: "Mundang (Cameroon)", value: "mua-CM" },
  { label: "Maka (Cameroon)", value: "mcp-CM" },
  { label: "Tikar (Cameroon)", value: "tik-CM" },
  { label: "Ghomala (Cameroon)", value: "bbj-CM" },
  { label: "Somali", value: "so" },
  { label: "Somali (Somalia)", value: "so-SO" },
  { label: "Somali (Ethiopia)", value: "so-ET" },
  { label: "Somali (Kenya)", value: "so-KE" },
  { label: "Zulu", value: "zu" },
  { label: "Zulu (South Africa)", value: "zu-ZA" },
  { label: "Xhosa", value: "xh" },
  { label: "Xhosa (South Africa)", value: "xh-ZA" },
  { label: "Azerbaijani", value: "az" },
  { label: "Azerbaijani (Azerbaijan)", value: "az-AZ" },
  { label: "Armenian", value: "hy" },
  { label: "Armenian (Armenia)", value: "hy-AM" },
  { label: "Georgian", value: "ka" },
  { label: "Georgian (Georgia)", value: "ka-GE" },
  { label: "Kazakh", value: "kk" },
  { label: "Kazakh (Kazakhstan)", value: "kk-KZ" },
  { label: "Uzbek", value: "uz" },
  { label: "Uzbek (Uzbekistan)", value: "uz-UZ" },
  { label: "Mongolian", value: "mn" },
  { label: "Mongolian (Mongolia)", value: "mn-MN" },
  { label: "Khmer", value: "km" },
  { label: "Khmer (Cambodia)", value: "km-KH" },
  { label: "Lao", value: "lo" },
  { label: "Lao (Laos)", value: "lo-LA" },
  { label: "Burmese", value: "my" },
  { label: "Burmese (Myanmar)", value: "my-MM" },
  { label: "Haitian Creole", value: "ht" },
  { label: "Haitian Creole (Haiti)", value: "ht-HT" },
  { label: "Luxembourgish", value: "lb" },
  { label: "Luxembourgish (Luxembourg)", value: "lb-LU" },
];
